internal/commands/server/k8s_e2e_test.go, internal/k8s/reconciler/http_route.go, internal/k8s/reconciler/http_route_test.go, internal/k8s/reconciler/route.go
This PR adds support for the `PrefixPath` routing that was, unfortunately overlooked during initial development. Additionally, there was a bug with the way we were tracking `HTTPRoute` rules that have multiple rule entries, where the services specified as `backendRefs` across the entire set of `rules` get combined into the final rule specified, and config entries were created solely for this rule.
The fixes:
1. Add a map entry for `PrefixPath` in our `HTTPRoute` --> internal representation code
2. Make a copy of the route rule as we're resolving services -- the iterating loop was taking an address of a value returned via a `range` operation, which was making all of the map keys the same.
Added unit tests and verified manually.
Checklist:
=> Fix up routing resolution behavior

.github/workflows/build.yml, .release/ci.hcl, .release/security-scan.hcl
What this PR does is it enables security scanning (owned by the Security team) for this repository. This is a part of the Common Release Tooling (CRT) effort `which enables a consistent workflow for security scanning that can be used across products and services. It provides a single abstraction point to allow us integrate our own scanning capabilities, as well as leverage external tools and APIs from vendors, open source, or free-to-use projects.` Learn more about HashiCorp's security-scanner [here](https://github.com/hashicorp/security-scanner/).
If anyone needs any further clarification or if nothing makes sense, feel free to comment or reach out to me! ❤️
I ran the tests in crt-workflows-common and the passing tests are as follows: …
=> Enabling Security-Scan for CRT

config/rbac/role.yaml, internal/adapters/consul/http.go, internal/adapters/consul/sync.go, internal/commands/server/command.go, internal/commands/server/k8s_e2e_test.go, internal/consul/config_entries.go, internal/core/tcp.go, internal/k8s/controller.go, internal/k8s/controllers/tcp_route_controller.go, internal/k8s/gatewayclient/gatewayclient.go, internal/k8s/gatewayclient/mocks/gatewayclient.go, internal/k8s/reconciler/config/errors.yaml, internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/listener.go, internal/k8s/reconciler/route.go, internal/k8s/reconciler/tcp_route.go, internal/k8s/reconciler/zz_generated_errors.go, internal/k8s/reconciler/zz_generated_errors_test.go, internal/k8s/service/resolver.go, internal/store/interfaces.go, internal/store/memory/gateway.go, internal/testing/e2e/consul.go, internal/testing/e2e/kind.go, internal/testing/e2e/kubernetes.go, internal/testing/e2e/service.go
This PR introduces the Gateway API's `TCPRoute`s -- in the process of implementation I also found a bug in how we were setting binding/resolution errors in our route statuses and went ahead and fixed that.
There are two implementation-specific constraints for `TCPRoute`s that I added. Due to the way Consul `IngressGateway` config entries only support single services when they leverage the TCP protocol:
1. `TCPRoute`s may only have a single backend service, which means
a. Only a single routing rule can be defined on a `TCPRoute`
b. The single routing rule can only have a single entry in `backendRefs`
2. The spec doesn't specify what to do with multiple `TCPRoute`s that reference the same Gateway listener, because of the need for only a single backend, we mark the listener status with …
=> Initial TCPRoute Implementation

internal/consul/certmanager.go, internal/consul/certmanager_test.go
The description of the issue is in the comment on the workaround/fix -- we basically force a blocking query timeout prior to kicking off the cert watching goroutines to make sure we successfully retrieve the leaf cert prior to blocking until rotation. Communicated the issue upstream so that we can get a fix in core as well.
Deployed a gateway talking to Consul 1.11 -- restarted the gateway a few times and made sure it always retrieved the certificates.
Workaround for https://github.com/hashicorp/consul/issues/12048
=> Fix Consul 1.11 certificate write blocking issues

config/crd/bases/api-gateway.consul.hashicorp.com_gatewayclassconfigs.yaml, config/rbac/role.yaml, internal/k8s/controllers/gateway_controller.go, internal/k8s/gatewayclient/gatewayclient.go, internal/k8s/gatewayclient/mocks/gatewayclient.go, internal/k8s/reconciler/gateway.go, pkg/apis/v1alpha1/types.go
Allow for an option on the `GatewayClassConfig` object to create a service account per-gateway deployment (useful for scoped consul permissions via auth methods)
```diff
diff --git a/dev/config/k8s/consul-api-gateway.yaml b/dev/config/k8s/consul-api-gateway.yaml
index d952bd1..87599a3 100644
--- a/dev/config/k8s/consul-api-gateway.yaml
+++ b/dev/config/k8s/consul-api-gateway.yaml
@@ -10,6 +10,8 @@ spec:
consul:
scheme: https
caSecret: consul-ca-cert
+    authentication:
+      managed: true
ports:
http: 8501
grpc: 8502
```
Run:
```bash
➜  consul-api-gateway git:(managed-service-account) ✗ kubectl apply -f dev/config/k8s/consul-api-gateway.yaml
...
➜  consul-api-gateway git:(managed-service-account) ✗ kubectl get pod -o json $(kubectl …
```
=> Add service account management

internal/commands/server/command.go
As part of the changes to https://github.com/hashicorp/consul-api-gateway/pull/72 the use of `flagConsulHTTPS` got dropped, as for auto-encrypt we are going to integrate tightly with `consul-k8s` and leverage their CA injection utilities. This cleans up a linter error that for some reason the PR didn't find but is now failing in main.
=> Fix linter error

config/rbac/role.yaml, internal/k8s/controllers/gateway_controller.go
The k8s client abstraction in consul-api-gateway [expects](https://github.com/hashicorp/consul-api-gateway/blob/c82e707fb30bebf1a88980568e0f67e318f65496/internal/k8s/gatewayclient/gatewayclient.go#L67-L68) to be able to create **or update** k8s `Deployments` and `Services`; however, the `ClusterRole` as defined today does not allow for updates to these resources. This prevents the Consul API Gateway controller from successfully installing a new gateway to the cluster.
- Modify `ClusterRole` to allow controller to update k8s `Deployment`
- Modify `ClusterRole` to allow controller to update k8s `Service`
Applied changes to deployment on GKE
Follow the [Learn …
=> Allow API Gateway controller to update k8s Deployments + Services

internal/k8s/service/resolver.go
Fixes #87
- Include the namespace and name of the service for which resolution failed
Checklist:
=> Include service namespace and name in resolution errors

config/base/gateway-class-config.yaml, dev/config/k8s/consul-api-gateway.yaml, internal/k8s/builder/testdata/tls-cert.yaml
- Remove extraneous references to `caSecret` (removed in https://github.com/hashicorp/consul-api-gateway/pull/72) per feedback in https://github.com/hashicorp/consul-api-gateway/pull/89#pullrequestreview-876557387
=> config: remove unused caSecret field

internal/testing/e2e/consul.go, internal/testing/e2e/gateway.go, internal/testing/e2e/service.go
- Use updated terminology from [Consul docs](https://www.consul.io/docs/security/acl/acl-system#builtin-tokens):
> In Consul 1.4 - 1.10, this was called the master token. It was renamed to initial_management token in Consul 1.11.
Checklist:
=> Use updated "initial management token" terminology

README.md, assets/logo.svg
- Updates README header with logo to align with format in hashicorp/consul#12285 and hashicorp/consul-k8s#1028
=> readme: update header with logo

dev/run
- Bump to latest version of Consul Helm chart in dev `run` script
```shell
$ ./dev/run
```
Run the above command on this branch
Checklist:
=> Consume v0.40.0 of Consul Helm chart in dev run script

internal/commands/server/k8s_e2e_test.go, internal/k8s/controller.go, internal/k8s/controllers/gateway_class_config_controller.go, internal/k8s/controllers/gateway_class_config_controller_test.go, internal/k8s/gatewayclient/gatewayclient.go, internal/k8s/gatewayclient/gatewayclient_test.go, internal/k8s/gatewayclient/mocks/gatewayclient.go
Fixes #88 
- When a `GatewayClassConfig` changes, evict all `GatewayClasses` that reference it from the cache
See instructions in #88 
Do the following on both main and this branch, observing that the config annotation on the `Gateway` is correct on this branch:
```shell
$ ./dev/run
$ kubectl apply -f ./dev/config/k8s/
$ kubectl get gateway test-gateway -o yaml
$ kubectl edit gatewayclassconfig test-gateway-class-config
$ kubectl delete gateway test-gateway
$ kubectl apply -f ./dev/config/k8s/
$ kubectl get gateway test-gateway -o yaml
$ ./dev/run -r
```
Checklist:
> Entries should use present tense (e.g. Add support …
=> Prevent stale GatewayClassConfig

internal/k8s/builder/builder.go, internal/k8s/builder/testdata/clusterip.deployment.golden.yaml, internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml, internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml, internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
I don't particularly like how this default is buried a few directories deep, but reorganizing that feels out of scope for now.
- Bumps the default Envoy image used to `envoyproxy/envoy:v1.20-latest`
**How I've tested this PR:** 
**How I expect reviewers to test this PR:**
**Checklist:**
=> envoy: bump default image to v1.20-latest

internal/testing/e2e/service.go
Followup to #107, missed a spot in e2e tests (this should likely be refactored eventually to just use the default value).
=> test/e2e: bump envoyImage to v1.20-latest

Makefile
- Update the Makefile `ctrl-test` task to follow the documentation at https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest (currently the attempted download path fails with a `404: Not found` from `curl` because this utility was refactored).
**How I've tested this PR:**
Ran `make ctrl-test` locally.
The diff this creates (unexpectedly?) removes `caSecret` from our GatewayClass configs YAML
```
caSecret:
description: The location of a secret to mount with the Consul
root CA.
type: string
```
and (not suprisingly) adds a Go 1.7-style build tag 
```
@ pkg/apis/v1alpha1/zz_generated.deepcopy.go:1 @
//go:build !ignore_autogenerated
// +build !ignore_autogenerated
```
**How I expect reviewers to test this PR:**
Offer feedback on …
=> makefile: update setup-envtest install task

.github/workflows/ci.yml, dev/docs/example-setup.md, internal/testing/e2e/consul.go
- Consume Consul 1.11.4 for tests and examples
- CI pipeline
- Ran through this tutorial https://learn.hashicorp.com/tutorials/consul/kubernetes-api-gateway with the consul version pointed at 1.11.4 and saw no errors
Confirm CI is pasing
Checklist:
=> Consume Consul 1.11.4 in tests and examples

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
- Consistify formatting of section headings across templates
- Consolidate "community note" content into [`CONTRIBUTING.md`](https://github.com/hashicorp/consul-api-gateway/blob/gh/update-templates/.github/CONTRIBUTING.md)
- Minor copy fixes
=> github: update issue and PR templates

CHANGELOG.md, internal/k8s/gatewayclient/gatewayclient.go, internal/k8s/gatewayclient/mocks/gatewayclient.go, internal/k8s/reconciler/listener.go, internal/k8s/reconciler/listener_test.go, internal/k8s/reconciler/utils.go, internal/k8s/reconciler/utils_test.go, internal/store/interfaces.go, internal/store/memory/gateway.go, internal/store/memory/store.go, internal/store/mocks/interfaces.go
Fixes #117 
- When a namespace selector is used for `allowedRoutes`, apply selector to route's `Namespace` instead of route itself
**How I've tested this PR:**
`$ kubectl apply -f` [these resources](https://gist.github.com/nathancoleman/2ca0983051287e7d9a3152f526284320).
With this change in the controller, the `HTTPRoute` will successfully attach to the `Gateway`. Without this change, it will not and you will see the log from #117 in the controller pod.
**How I expect reviewers to test this PR:**
**Checklist:**
=> Apply namespace selector to namespace instead of route

config/rbac/role.yaml, internal/k8s/controllers/gateway_controller.go
Something I remembered a bit too late for #119 
- Add RBAC permissions for controller to retrieve namespaces (caching logic also requires `watch`)
Ran locally using `./dev/run` and installed `HTTPRoute` in separate namespace from gateway w/ selector for allowed routes
=> Allow API Gateway controller to retrieve namespaces

internal/commands/server/k8s_e2e_test.go, internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/gateway_test.go, internal/k8s/reconciler/manager_test.go
Fixes #116
- Assign the external IP of a `Service` to `Gateway` instead of pod IP when service type is `LoadBalancer`
- Wait to mark `Gateway` ready until `Service` is available and has the necessary exposed IP
=> Assign appropriate IP to Gateway

CHANGELOG.md, internal/adapters/consul/http.go, internal/adapters/consul/sync.go, internal/commands/server/k8s_e2e_test.go, internal/testing/e2e/consul.go, internal/testing/e2e/kind.go
This PR changes the way that HTTP routes are merged. Specifically, rather than looking at the totality of the hostnames used in a particular route, it attempts to merge all routes that reference a given hostname before prioritizing the individual rules on a route. A good, stripped-down example of how this should work is found in the [conformance tests](https://github.com/kubernetes-sigs/gateway-api/blob/master/conformance/tests/httproute-matching-across-routes.yaml):
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
...
spec:
hostnames:
- example.com
- example.net
...
rules:
- matches:
- path:
type: PathPrefix
value: /
...
backendRefs:
- name: infra-backend-v1
...
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
...
spec:
hostnames:
- example.com
... …
```
=> Fix how http routes are merged

internal/store/memory/store.go
Something unexpected that I discovered while using the go-multierror library in a personal project:
Use `ErrorOrNil()` when asserting no errors from `multierror.Group`.
See docstring for `ErrorOrNil()` [here](https://github.com/hashicorp/go-multierror/blob/9974e9ec57696378079ecc3accd3d6f29401b3a0/multierror.go#L24-L28).
This test fails every time
```go
func TestMultierrorGroupWait(t *testing.T) {
var g multierror.Group
g.Go(func() error { return nil })
require.NoError(t, g.Wait())
}
```
This one behaves as you'd expect
```go
func TestMultierrorGroupWait(t *testing.T) {
var g multierror.Group
g.Go(func() error { return nil })
require.NoError(t, g.Wait().ErrorOrNil())
}
```
> Entries should use imperative present …
=> Use ErrorOrNil for asserting no errors in multierror group

internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/gateway_test.go, internal/k8s/utils/versions.go, internal/store/interfaces.go, internal/store/memory/gateway.go, internal/store/memory/store.go, internal/store/mocks/interfaces.go
We currently wind up with a stale gateway in memory that can't be written to the store when we want to update it.
```logs
2022-03-15T17:56:05.165Z [ERROR] memory/store.go:110: consul-api-gateway-server.state: error syncing gateways:
error=
| 1 error occurred:
| 	* Operation cannot be fulfilled on gateways.gateway.networking.k8s.io "backend-namespaces": the object has been modified; please apply your changes to the latest version and try again
| 
```
Due to this, the new route that's being added is unable to bind and thus the conformance tests fail.
After adding some code using [go-test/diff](https://github.com/go-test/deep), I was able to determine the diff between the gateway `Listeners()` during the sync process:
```diff
slice[0].gateway.ObjectMeta.Annotations.map[api-gateway.consul.hash …
```
=> Simplify comparison of gateways to use only resource version

internal/k8s/reconciler/gateway.go
Remove unused func causing linting to fail on `main` [here](https://github.com/hashicorp/consul-api-gateway/runs/5606501755?check_suite_focus=true)
linting passes on this PR
=> Remove now-unused func

dev/docs/supported-features.md
The `HTTPRoute` can now get `RefNotPermitted` in its status. This error was added in #143.
This PR updates the list of supported features.
Read it
=> Add RefNotPermitted to status listing for HTTPRoute

.changelog/143.txt
-Change release note entry for reference policy from feature to breaking change
=> ReferencePolicy should be breaking change in changelog

.github/workflows/ci.yml
This adds some CI targets for Consul 1.12.0-beta1 and has us testing on the latest 1.11 patch release. Once the 1.12 release goes out we can probably drop the 1.11 targets from the build matrix.
=> Rev CI versions for consul 1.11 and add 1.12 beta

.github/workflows/conformance.yml
Rather than have to manually add in a tmate session to debug failing runs, allow a manual run to start up tmate whenever any step fails. This will add an option when running manually such as the ones seen [here](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/).
If you go to the Actions tab for the repo and choose to run the conformance workflow on this branch, you'll see this nice new setting:
=> Allow manual conformance runs to start tmate session on failure

internal/testing/conformance/consul-config.yaml
Consume consul 1.12.0-beta1 for conformance testing until the updating of consul-k8s next week
🤖 tests pass
=> Consume consul 1.12.0-beta for conformance testing

internal/adapters/consul/sync.go, internal/adapters/consul/sync_test.go, internal/commands/server/server.go, internal/testing/e2e/gateway.go
Since the `ConsulSyncAdapter` resides in the `consul` package, we can simplify the name to `SyncAdapter` which makes things less verbose while conveying the same thing.
CI
CI
=> Simplify naming of sync adapter in consideration of pkg name

.github/actions/setup-kind/action.yml, .github/workflows/conformance.yml
Shifting steps to setup a Kind cluster over into their own action.
This gets us one step closer to having what's essentially a test matrix for e2e+conformance where we vary the type of cluster across a list of setup actions in the future:
- `setup-kind/action.yml`
- `setup-eks/action.yml`
- `setup-gke/action.yml`
- `setup-aks/action.yml`
:robot: tests pass
=> Consolidate steps for Kind setup into single action

internal/envoy/manager.go, internal/envoy/testdata/basic.golden.json, internal/envoy/testdata/empty.golden.json, internal/envoy/testdata/sds.golden.json, internal/envoy/testdata/tls.golden.json
Consul-K8s moved to Envoy 1.22 which includes a [minor behavior change](https://www.envoyproxy.io/docs/envoy/v1.22.0/version_history/current#minor-behavior-changes) that breaks due to our current bootstrap config:
> config: type URL is used to lookup extensions regardless of the name field. This may cause problems for empty filter configurations or mis-matched protobuf as the typed configurations. This behavioral change can be temporarily reverted by setting runtime guard envoy.reloadable_features.no_extension_lookup_by_name to false.
🤖 conformance tests pass where they fail before
=> Specify explicit type config for Envoy bootstrap filters

.changelog/162.txt, internal/commands/server/k8s_e2e_test.go, internal/k8s/controllers/http_route_controller_test.go, internal/k8s/controllers/tcp_route_controller.go, internal/k8s/controllers/tcp_route_controller_test.go, internal/k8s/gatewayclient/gatewayclient.go, internal/k8s/gatewayclient/gatewayclient_test.go, internal/k8s/gatewayclient/mocks/gatewayclient.go, internal/k8s/gatewayclient/test_helpers.go, internal/testing/e2e/consul.go, internal/testing/e2e/kind.go
Adds ReferencePolicy lifecycle watch to TCPRouteController. Refs #156 
- Validate that tests offer sufficient coverage.
- Offer any suggestions on how best to avoid the `gatewayclient` <> `k8stest` import cycle
=> TCPRouteController: watch ReferencePolicy lifecycle

.changelog/167.txt, .github/workflows/ci.yml, .github/workflows/conformance.yml, go.mod, go.sum, internal/commands/server/k8s_e2e_test.go
- Bump `GO_VERSION` for CI to 1.18
- Bump the `reflect2` dependency to avoid a segfault
Running `go test ./...` in `internal/k8s/builder` previously failed with a segfault when running with Go 1.18 locally due to unsafe code used by the `reflect2` package (an indirect dependency from Kubernetes core). With this change tests now pass locally, and should be able to pass in CI as well.
- Confirm that bumping the version in `go.mod` is not necessary as we aren't actually using any features like generic that require Go 1.18 yet, just fixing compatibility.
- Did I miss anywhere this needs to be bumped, e.g. for release pipelines?
=> ci: bump Go version to 1.18

.changelog/187.txt, internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/gateway_test.go
This adds hostname values to addresses for a loadbalancer. In particular this is necessary for AWS EKS. In EKS LoadBalancers get "ExternalP" values that aren't actually IP addresses, but rather are hostnames. This is accounted for in the underlying `Service.Status.LoadBalancer.Ingress[*].Hostname` fields.
The problem is two-fold. In EKS LoadBalancer have hostnames rather than ips, so we:
1. Were never getting a valid ExternalIP value for the gateway address, and
2. Since we didn't have an empty string check on the IP, were attempting to append an empty value onto the gateway addresses.
This was resulting in the following error:
```
2022-04-29T03:20:58.298Z [ERROR] k8s/logger.go:23: consul-api-gateway-server.controller-runtime.controller.gateway: Reconciler error: …
```
=> Bug: LoadBalancers - Use Hostnames in addition to IP

.github/workflows/build.yml
Refs https://github.com/hashicorp/consul-api-gateway/pull/167#issuecomment-1115079861 (which already added a changelog entry for this)
=> ci: update binary build Go version to 1.18.1

internal/testing/conformance/consul-config.yaml
Specify `consul-k8s-control-plane:latest` image to support installing from Consul Helm chart main branch.
Running conformance tests, which have been failing in the setup steps (`consul-controller` and `conect-inject-controller` pods never become healthy) with `Parsing flagset: flag provided but not defined: -consul-api-timeout` due to changes in the `main` branch of the Consul Helm chart but `imageK8s` defaulting to [`0.43.0`](https://github.com/hashicorp/consul-k8s/blob/dc7f08965c01d2180813d0d83539a49bcc60a7d3/charts/consul/values.yaml#L110) still.
Confirm that conformance tests are able to deploy Consul from the Helm chart successfully, and reach _expected_ failures in ReferencePolicy conformance test suite.
> …
=> conformance: specify consul-k8s-control-plane:latest

internal/commands/server/k8s_e2e_test.go
- Refactor `checkGatewayConfigAnnotation` to get the gateway resource directly rather than relying on passing in an updated gateway resource as a side effect of a prior check.
- Fixes an incorrect assertion and removes substantial redundant checks from TestGatewayWithClassConfigChange
- Minor refactor to pass `resources.Resources` instead of `*envconf.Config` into `createGatewayClass` and `createGateway` helpers, clean up many tests to use these helpers when possible.
The motivation for this was stumbling over writing a new test with a similar two gateway setup - finding several redundant checks and spending too long figuring out why things weren't working as expected when deleting the verbose checks in favor of the streamlined helpers (the subsequent `checkGatewayConfigAnnotation` checks …
=> e2e: fixup checkGatewayConfigAnnotation and clean up TestGatewayWithClassConfigChange

.changelog/154.txt, internal/k8s/reconciler/config/errors.yaml, internal/k8s/reconciler/listener.go, internal/k8s/reconciler/listener_test.go, internal/k8s/reconciler/route.go, internal/k8s/reconciler/utils.go, internal/k8s/reconciler/utils_test.go, internal/k8s/reconciler/zz_generated_errors.go, internal/k8s/reconciler/zz_generated_errors_test.go
When a listener on a `Gateway` contains a `certificateRef` from a different namespace, require applicable `ReferencePolicy`. The expectations for the listener status in the scenario are described [here](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#:~:text=References%20to%20a,the%20%E2%80%9CInvalidCertificateRef%E2%80%9D%20reason.).
<details>
<summary>Example</summary>
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
name: example-gateway
namespace: default
spec:
gatewayClassName: consul-api-gateway
listeners:
- protocol: HTTPS
port: 8443
name: https
allowedRoutes:
namespaces:
from: Same
tls:
certificateRefs:
- name: consul-server-cert
namespace: consul
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferencePolicy
metadata:
name: …
```
=> Require ReferencePolicy for certificateRef in other namespace

.changelog/197.txt, go.mod, go.sum, internal/commands/server/k8s_e2e_test.go, internal/store/memory/gateway.go, internal/testing/e2e/consul.go, internal/testing/e2e/kind.go
Removes a route from a listener if it fails to bind when reconciling. Fixes an issue where deleting a ReferencePolicy would update the route status, but the stale route would not be removed from the gateway listener.
As an aside, the `(bool, error)` return of `CanBind` seems redundant and makes it prone to misuse - should it be changed to just one of those values instead of the tuple?
- Review the test additions/changes.
- Confirm that a gateway removes a stale route and stops routing traffic after a route is invalidated by being modified or having a ReferencePolicy that affects it deleted.
- The `checkRouteError` function and only looking for an empty string TCP response feel like quite crude checks, is there a better way to handle these?
- `TestRouteParentRefChange` contains the …
=> store: remove route from listener when not able to bind

internal/testing/e2e/consul.go
Abstract out the same few repeated lines of test environment assertion into a one-line function call 
- 🤖 still passes for e2e tests
See above
=> Clean up repeated test environment assertions

.changelog/200.txt, internal/commands/server/k8s_e2e_test.go, internal/store/memory/gateway.go
Fixes the following issue:
Updates test to document currently-expected behavior but not fixed yet - after discussing with @nathancoleman we believe support for multiple gateways is not yet implemented rather than a "bug":
- Traffic _does_ still route successfully through the first gateway after adding the second gateway ParentRef
Written e2e test assertions that demonstrate broken behavior when changing the ParentRef of a route.
Confirm that new test assertions demonstrate intended functionality, review fixes.
=> fix listener and route behavior when changing ParentRef

.github/workflows/ci.yml
- Remove flaky Consul install using https://github.com/nickethier/action-setup-hashicorp-tool
- Install binary directly with `curl` instead
- Let CI tests run and confirm they don't fail on downloading Consul binary
- Confirm that CI tests are less flaky with this approach
=> ci: remove broken Consul binary install

go.mod, go.sum
Our current version of Testify is pulling in a version of `gopkg.in/yaml.v3` that contains [CVE-2022-28948](https://github.com/advisories/GHSA-hp87-p4gw-j4gq). The latest version of testify resolves this by updating its `yaml.v3` dependency w/ https://github.com/stretchr/testify/pull/1192
```shell
$ go mod why gopkg.in/yaml.v3
github.com/hashicorp/consul-api-gateway/internal/adapters/consul
github.com/hashicorp/consul-api-gateway/internal/adapters/consul.test
github.com/stretchr/testify/assert
gopkg.in/yaml.v3
```
=> Update testify to version that resolves CVE-2022-28948

.changelog/225.txt, internal/consul/certmanager.go, internal/envoy/middleware.go, internal/envoy/mocks/sds.go, internal/envoy/sds.go, internal/envoy/sds_test.go
When users use root connect certificates without SPIFFE information (i.e. via Vault), the controller crashes. This removes the piece of code in our mTLS middleware that verifies the corresponding host between root cert and the derived leaf cert. This should be alright since we're still validating that the root actually generated the leaf certificate cryptographically before these checks.
Fixes: https://github.com/hashicorp/consul-api-gateway/issues/208
=> Fix SPIFFE url handling

.github/workflows/prepare_release.yml
Followup to #186 
For less-trusted verified and third party actions, our internal recommendation is to pin to the full commit SHA instead of the mutable version tag.
Check referenced actions repos to verify commit SHA matches tag we were previously using
See above
=> Pin less-trusted actions to full commit SHA

.changelog/changelog.tmpl
Fix whitespace inconsistency for `NOTES` section header of generated changelog
Compare whitespace operator for `NOTES` to other section headers
See above
=> Make whitespace chomp for NOTES in changelog consistent

.github/workflows/conformance.yml, .github/workflows/conformance_with_build.yml, internal/testing/conformance/consul-config.yaml
Our heavy conformance workflow that targets EKS and, in the future, GCP and Azure, can only test builds from our main branch. Due to this, it's misleading if triggered on a PR via a label.
This workflow uses the same "building blocks" we use in our normal workflow; however, it will build the branch being run against and target that build for conformance tests. We will use this for PRs and runs against specific branches.
🤖  tests pass
See above
=> Add lightweight conformance workflow that builds image for test

Makefile
Adding the third of three packages containing golden files [here](https://github.com/hashicorp/consul-api-gateway/tree/main/internal/adapters/consul/testdata) that occasionally need to be regenerated
After making a change to a source file in this package's `testdata`:
```shell
$ make generate-golden-files
```
See above
=> Add missing package for `make generate-golden-files`

.github/actions/setup-eks/action.yml, .github/actions/setup-eks/cluster.tf, .github/actions/teardown-eks/action.yml, .github/workflows/conformance.yml
Use Terraform instead of eksctl to manage our EKS cluster for conformance tests.
The main driver here is that eksctl frequently leaves orphaned resources that we have to manually clean up.
In addition, this gives us a workflow that's easily adaptable for GKE and AKS in the near future.
See successful conformance EKS run on 0898eefcada0180e18cc4ee78ce4ed86f3824300
See above
=> Use Terraform for conformance tests on EKS

.github/workflows/prepare_release.yml
Taking advantage of the new [job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) feature and output a link to PR changes so we don't have to dig into logs.
=> Add link to create PR to job output for release prep workflow

internal/k8s/gatewayclient/gatewayclient.go
The ReferencePolicy needs to be included for backward compatibility; however, it couldn't be included until v0.5.0-rc2 of kubernetes-sigs/gateway-api which restored the ReferencePolicy CRD to the default set and fixed a listing bug.
v0.5.0-rc2 was consumed in #279, but I wasn't aware of this related TODO until I attempted the [Learn guide](https://learn.hashicorp.com/tutorials/consul/kubernetes-api-gateway) which still uses the deprecated `ReferencePolicy` instead of the new `ReferenceGrant`.
See above
=> Restore inclusion of ReferencePolicy in Grant lookup

.changelog/283.txt, config/crd/kustomization.yaml, go.mod, go.sum
Consume latest release of https://github.com/kubernetes-sigs/gateway-api.
Code is largely identical to the RC2 release consumed in #279 .
🤖 tests pass
See above
=> Consume kubernetes-sigs/gateway-api v0.5.0

.changelog/290.txt, internal/k8s/reconciler/config/statuses.yaml, internal/k8s/reconciler/route.go, internal/k8s/reconciler/zz_generated_status.go, internal/k8s/reconciler/zz_generated_status_test.go, internal/k8s/service/resolver.go, internal/k8s/service/resolver_test.go
The contract for `HTTPBackendRef` has changed to include a new reason, `InvalidKind`, for the `ResolvedRefs` condition when an unknown or unsupported backendRef kind is used ([docs](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPBackendRef)). This change set implements that reason.
Created HTTPRoute w/ unknown/unsupported kind for `backendRef`, verifying that the new `InvalidKind` reason is assigned to the status.
<details>
<summary>Example</summary>
By making a small change to the `backendRef` on this HTTPRoute from the Learn guide:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
name: example-route-2
namespace: consul
spec:
parentRefs:
- name: api-gateway
rules:
- matches:
- path:
type: PathPrefix
value: / …
```
=> Implement InvalidKind reason for unknown/unsupported backendRef kind

.changelog/291.txt, internal/commands/server/k8s_e2e_test.go, internal/k8s/reconciler/config/statuses.yaml, internal/k8s/reconciler/route.go, internal/k8s/reconciler/zz_generated_status.go, internal/k8s/reconciler/zz_generated_status_test.go, internal/k8s/service/resolver.go, internal/k8s/service/resolver_test.go
> Will want to review + merge #290 first which this PR is based on
The contract for `HTTPBackendRef` has changed to include a new reason, `BackendNotFound`, for the `ResolvedRefs` condition when a known backendRef kind is used but the backend does not exist ([docs](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPBackendRef)). This change set implements that reason.
Created HTTPRoute w/ non-existent `Service` for `backendRef`, verifying that the new `BackendNotFound` reason is assigned to the status.
<details>
<summary>Example</summary>
By making a small change to the `backendRef` on this HTTPRoute from the Learn guide:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
name: example-route-2
namespace: consul
spec: …
```
=> Implement BackendNotFound reason for backendRef that does not exist

.changelog/278.txt, internal/commands/server/k8s_e2e_test.go, internal/commands/server/server.go, internal/consul/intentions.go, internal/store/memory/gateway.go, internal/store/memory/store.go, internal/testing/e2e/gateway.go
This is longer-term followup based on https://github.com/hashicorp/consul-api-gateway/issues/230#issuecomment-1157976119
Trigger a sync for our in-memory store at a constant interval in the background
_Still working on how to test this in a programmatic fasion_
=> Sync in-memory store w/ Consul at constant interval

internal/commands/server/k8s_e2e_test.go, internal/k8s/controllers/gateway_controller_test.go, internal/k8s/controllers/tcp_route_controller.go, internal/k8s/gatewayclient/gatewayclient.go
- To match https://github.com/hashicorp/consul-api-gateway/blob/main/internal/k8s/controllers/http_route_controller.go#L141, possible since ReferencePolicy now uses ReferenceGrantSpec internally as the type of its `Spec` field.
CI tests should still be passing after changes.
Verify changes make sense and sufficiently cover support.
=> referencepolicy: finish backwards compatibility support and tests

internal/envoy/mocks/secrets.go, internal/envoy/sds.go, internal/envoy/secrets.go, internal/envoy/secrets_test.go
- To account for the fact that certs can technically be rotated at any time, after a set interval force a repull of all certificates being watched. 
- Tests pass
- Locally using Hashiqube to run vault and kind to run api gateway
- Tests pass
- [ X ] Tests added
=> TLS Watch and Rotate

.changelog/308.txt, internal/commands/server/k8s_e2e_test.go, internal/consul/intentions.go
Our CAS operation for updating intentions was broken because it was using the wrong config entry index. The result is that if multiple gateways bound to a single service then intentions for the second gateway weren't being properly created. This changes the sync code to use the proper index.
Manually and updated tests.
=> Fix intention syncing CAS index

.changelog/307.txt, .github/workflows/ci.yml, .github/workflows/conformance.yml, .github/workflows/conformance_with_build.yml
Refs https://github.com/hashicorp/consul-api-gateway/pull/303#issuecomment-1211339214
Running CI unit, e2e and conformance tests for all supported versions.
Confirm that mitigations for new behavior are understood and acceptable. Do we want to check upstream Consul core per-commit builds in regular CI, or only nightly conformance?
=> ci: add Consul v1.13 and 1.14-dev edge builds to test matrices

CHANGELOG.md, README.md, config/deployment/deployment.yaml, dev/docs/example-setup.md, dev/docs/supported-features.md
Consul API Gateway version being released: `0.4.0`
Now requires:
- consul: `1.11.2`
- consul-k8s: `0.47.1`
=> Prepare for release of v0.4.0

internal/k8s/builder/testdata/clusterip.deployment.golden.yaml, internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml, internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml, internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml, internal/version/version.go
This allows work in progress to be correctly tagged as v0.5.0-dev
Bump version to reflect next minor release
```
$ make version
```
=> Bump version to next minor release

internal/k8s/reconciler/deployer.go, internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/gateway_test.go, internal/k8s/reconciler/manager.go, pkg/apis/v1alpha1/types.go
In working to get the store refactor merged, this was one chunk of changes that I noticed could be broken out of https://github.com/hashicorp/consul-api-gateway/pull/160 to make reviews less taxing. This simply moves the logic for `Deployment`, `Service`, etc. creation into a new `GatewayDeployer`. This narrows the scope of responsibility for `K8sGateway`.
🤖 tests pass
=> Refactor deploy logic out of K8sGateway

internal/k8s/reconciler/common/utils.go, internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/gateway_test.go, internal/k8s/reconciler/listener.go, internal/k8s/reconciler/listener_test.go, internal/k8s/reconciler/route.go, internal/k8s/reconciler/state/gateway.go, internal/k8s/reconciler/status/equality.go, internal/k8s/reconciler/tls.go
In working to get the store refactor merged, this was one chunk of changes that I noticed could be broken out of https://github.com/hashicorp/consul-api-gateway/pull/160 to make reviews less taxing. This simply moves the state of the `K8sGateway` into a separate struct that can be serialized (important in the future).
🤖 tests pass
=> Refactor K8sGateway state into serializable struct

go.mod, go.sum
The current version of crypto contains the GO-2021-0356 vulnerability.
The version consumed in this PR has been patched.
https://deps.dev/advisory/osv/GO-2021-0356
Verify that the version consumed in this PR is listed as "patched" on the advisory linked above
See above
=> Update crypto package to fix GO-2021-0356

internal/k8s/reconciler/factory.go, internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/gateway_test.go, internal/k8s/reconciler/listener_test.go, internal/k8s/reconciler/manager.go, internal/k8s/reconciler/route.go, internal/k8s/reconciler/route_test.go, internal/k8s/reconciler/utils_test.go, internal/k8s/service/mocks/resolver.go, internal/k8s/service/resolver.go
In working to get the store refactor merged, this was one chunk of changes that I noticed could be broken out of https://github.com/hashicorp/consul-api-gateway/pull/160 to make reviews less taxing. This introduces a factory for creating Gateways and Routes.
🤖 tests pass
=> Introduce Factory for creating Gateways + Routes

internal/store/interfaces.go, internal/store/memory/backend.go, internal/store/memory/backend_test.go, internal/store/mocks/interfaces.go, internal/store/store.go
This is the first part to be broken out of #165 . This defines the new `Backend` interface that handles CRUD ops for Gateways and Routes. It's not yet consumed anywhere, so this code is dark. I will consume it in a future PR as part of the ongoing refactor.
🤖 tests pass
=> (dark) Add storage "backend" interface, in-memory implementation

.gitattributes, internal/k8s/reconciler/status/generator.go, internal/k8s/reconciler/status/zz_generated_status.go, internal/k8s/reconciler/status/zz_generated_status_test.go
This is the second part to be broken out of https://github.com/hashicorp/consul-api-gateway/pull/165 . This adds marshal/unmarshal funcs for the generated statuses by extending the generator.
🤖 tests pass
=> (dark) Include marshaling funcs when generating statuses

internal/k8s/reconciler/binder.go, internal/k8s/reconciler/binder_test.go, internal/k8s/reconciler/gateway.go
This is the fifth part to be broken out of https://github.com/hashicorp/consul-api-gateway/pull/165 . This restructures the `Binder` interface so that a single binder is reusable for multiple gateways instead of wrapping a single gateway.
🤖 tests pass
=> Refactor binder interface to be reusable for multiple gateways

internal/k8s/reconciler/binder_test.go, internal/k8s/reconciler/factory.go, internal/k8s/reconciler/gateway.go, internal/k8s/reconciler/manager.go, internal/k8s/reconciler/mocks/manager.go, internal/k8s/reconciler/route.go, internal/k8s/reconciler/route_test.go, internal/k8s/reconciler/validator/gateway.go, internal/k8s/reconciler/validator/gateway_test.go, internal/k8s/reconciler/validator/route.go, internal/k8s/reconciler/validator/route_test.go
This is the fourth part to be broken out of https://github.com/hashicorp/consul-api-gateway/pull/165 . This removes the validation entrypoint from the route + gateway themselves to further simplify them and instead calls the validator directly from the `ReconcileManager` before doing the upsert into the store.
🤖 tests pass
=> Move gateway + route validation up into reconcile manager

internal/k8s/reconciler/statuses.go, internal/k8s/reconciler/statuses_test.go
This is the eighth part to be broken out of https://github.com/hashicorp/consul-api-gateway/pull/165 . This takes code from `K8sGateway` and `K8sRoute` related to syncing statuses and moves it into a separate `StatusUpdater`.
🤖 tests pass
=> (dark) Refactor status syncing logic out of K8sGateway + K8sGateway into StatusUpdater

internal/api/server.go, internal/commands/controller/command.go, internal/commands/controller/health.go, internal/commands/exec/exec.go, internal/common/flags.go, internal/consul/registration.go, internal/consul/registration_test.go, internal/envoy/sds.go, main.go
This adds an entrypoint for the API server. As we flesh out the API implementation it'll need some tweaking, but for now it spins up a server based off of the configuration flags passed to it and a goroutine that registers the controller as a Consul service along with periodically updating the TTL health check it registers.
It also scaffolds out an entrypoint for returning controller "health" that we'll want to build an internal endpoint for that grabs all of the instance health from the controllers that have been registered in Consul.
Manually, here are some outputs/screenshots:
In one terminal:
```
➜  consul-api-gateway git:(vm-controller-cli-entrypoint) ./consul-api-gateway controller
```
In another:
```
➜  consul-api-gateway git:(vm-controller-cli-entrypoint) ./consul-api-gateway …
```
=> Add basic controller CLI entrypoint

internal/store/consul_backend.go, internal/store/consul_backend_test.go
Since @sarahalsmiller is out this week I just went ahead and threw this together to unblock some of our implementation work. This adds an implementation of a Consul-based `Backend` interface. A couple of things to note:
1. We'll want to touch up the `id` implementation for our core `Route` model to handle complex ids (rather than just be dumb strings) so that we can segment better in our storage layer -- right now since we don't have namespace data encoded in the ID we just stub out some of the values needed to construct the key path
2. We'll want to see whether or not we should separate out the TCP/HTTP implementations of our List/Upsert/etc. operations. This is a bigger issue that we can discuss now but can probably punt on similarly to how we talked about before in the PR that …
=> (dark) Initial Consul backend storage implementation

internal/store/memory_backend.go, internal/store/memory_backend_test.go
Move in-memory backend into `store` pkg alongside the Consul backend to simplify/normalize package structure.
🤖 tests pass
=> (dark) Move in-memory backend into store pkg alongside Consul backend

.changelog/368.txt, internal/commands/exec/command.go, internal/commands/exec/exec.go, internal/commands/server/command.go, internal/commands/server/server.go, internal/consul/certmanager.go, internal/k8s/builder/gateway.go, internal/k8s/controller.go, internal/k8s/reconciler/deployer.go, internal/k8s/reconciler/manager.go
Fixes #361 
In order to successfully watch root certs from a secondary datacenter, we must specify the name of the primary datacenter when setting up the watch. This requires that we accept the primary datacenter name as a flag when starting the controller. The other changes in this PR are just to plumb that value down into the watch initialization.
1. Federate between 2 Kubernetes clusters as described in [this guide](https://www.consul.io/docs/k8s/deployment-configurations/multi-cluster/kubernetes), making sure to enable API gateway in both the primary and secondary clusters
1. `apiGateway.enabled: true`
2. `apiGateway.image: hashicorp/consul-api-gateway:0.4.0`
3. `global.imageK8S: hashicorpdev/consul-k8s-control-plane:f1a9304a` (build from …
=> Specify primary datacenter for root cert watch

go.mod, go.sum, internal/api/server.go
Replace (accidental?) usage of `go-chi/chi` v1.5.4 with `go-chi/chi/v5`. Closes #348 
CI tests
Confirm using two different versions of this library was unintended and this resolution makes sense.
=> api: use chi/v5 everywhere

go.mod, go.sum
Update dependency with identified CVE GO-2022-0969
Verified the newly-consumed version is listed as patch/unaffected [here](https://deps.dev/advisory/osv/GO-2022-0969)
See above
=> Update dependency to resolve GO-2022-0969

.changelog/385.txt, Makefile
Switch from my personal fork back to the upstream go-changelog repo now that https://github.com/hashicorp/go-changelog/pull/22 has been merged.
Every CI run with a changelog entry will exercise this make task to validate it.
=> makefile: switch back from fork to main go-changelog repo

.github/workflows/conformance_with_build.yml
I kept misreading the `pr/run-conformance` label as "un-conformance", this updates the CI check to look for a `pr/conformance` label instead. We can keep both labels around temporarily to avoid requiring PRs before this change to rebase to run conformance tests.
Runs CI conformance tests with the `pr/conformance` label.
=> ci: switch to pr/conformance label

.github/workflows/ci.yml, internal/testing/e2e/kind.go, internal/testing/e2e/kubernetes.go
Kubernetes 1.24 no longer implicitly creates a `Secret` w/ a token in it when a `ServiceAccount` is created. This PR modifies our e2e tests to create the `Secret` explicitly which is the [documented solution](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#to-create-additional-api-tokens).
I found [this](https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0) to be a helpful explanation of what's happening.
> **Note** A pod running w/ the `ServiceAccount` still has a token mounted inside even though the `Secret` that previously contained this token is no longer created. This is why Consul API Gateway works on K8s 1.24 in a standard deployment; however, our e2e test deployment does not run inside a pod and so requires …
=> Update e2e tests to work on k8s 1.24

internal/k8s/builder/gateway.go, internal/k8s/builder/gateway_test.go, internal/k8s/reconciler/deployer.go
We have builder patterns that don't support method chaining which makes them feel awkward to use. This PR adds the parts needed for method chaining and removes some unused funcs on the builders. No functional impact.
🤖 tests pass
See above
=> Support method chaining in gateway builders

go.mod, go.sum, internal/tools.go
We don't actually import `mockgen` anywhere but depend on it as part of our toolchain. Since it isn't imported, `$ go mod tidy` will remove it from the modfile and causes failures in our unit test CI (examples [1](https://github.com/hashicorp/consul-api-gateway/actions/runs/3230554154/jobs/5289136204), [2](https://github.com/hashicorp/consul-api-gateway/pull/399), [3](https://github.com/hashicorp/consul-api-gateway/pull/415), etc.)
This fix is recommended by https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module, which I came across via https://github.com/google/wire/issues/299.
:robot: tests pass
See above
> commit the resulting file, which should have a name matching your PR …
=> Add tools.go to prevent mod from dropping tool-only dependencies

.changelog/412.txt, .github/workflows/ci.yml, .github/workflows/conformance.yml, go.mod, go.sum, internal/commands/server/k8s_e2e_test.go, internal/k8s/reconciler/validator/gateway.go, internal/k8s/reconciler/validator/gateway_test.go
Closes #396 
- Update InvalidCertificateRef error to RefNotPermitted to match the spec [#1351](https://github-redirect.dependabot.com/kubernetes-sigs/gateway-api/pull/1351)
- Update conformance test pin to pull in updated tests
- PR Passes
- [ X ] Tests added
=> Update InvalidCertificateRef error to RefNotPermitted

.changelog/371.txt, internal/commands/exec/exec.go
This swaps the health check that's registered as part of the exec process to use TTL-based checks in Consul.
=> Register via TTL check for nodes with no agents

.github/workflows/conformance_with_build.yml
Update the gateway-api branch used for PR conformance runs to match the nightly runs updated in #412 
🤖 tests
=> Update gateway-api pin for PR conformance runs

.changelog/433.txt, config/crd/bases/api-gateway.consul.hashicorp.com_gatewayclassconfigs.yaml, config/rbac/role.yaml, internal/k8s/controllers/gateway_controller.go, internal/k8s/gatewayclient/gatewayclient.go, internal/k8s/gatewayclient/mocks/gatewayclient.go, internal/k8s/reconciler/deployer.go, pkg/apis/v1alpha1/types.go, pkg/apis/v1alpha1/types_test.go
> **Note** Depends on the changes proposed in https://github.com/hashicorp/consul-k8s/pull/1672 which was recently merged.
When creating a `Deployment` for a given `Gateway`, we create a "managed" `ServiceAccount` if the `GatewayClassConfig` indicates that we should.
With the changes in this PR, we will also create a `Role` and `RoleBinding` attaching the named `podSecurityPolicy` from the `GatewayClassConfig` if one has been provided.
> **Note** For convenience, the Helm chart changes merged in https://github.com/hashicorp/consul-k8s/pull/1672 will create a `PodSecurityPolicy` that is reasonable for these deployments when `.Values.global.enablePodSecurityPolicies`; however, users may also create their own `PodSecurityPolicy` and reference that in the `GatewayClassConfig` if they wish. …
=> Accept PodSecurityPolicy name, bind to managed ServiceAccount if provided

Dockerfile, Dockerfile.local, internal/k8s/builder/gateway.go, internal/k8s/builder/testdata/clusterip.deployment.golden.yaml, internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml, internal/k8s/builder/testdata/max-instances.deployment.golden.yaml, internal/k8s/builder/testdata/min-instances.deployment.golden.yaml, internal/k8s/builder/testdata/multiple-instances.deployment.golden.yaml, internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml, internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml, internal/testing/e2e/consul.go, internal/testing/e2e/docker.go
To go along with the movement towards the use of `consul-server-connection-manager`, I noticed that to make the "exec" mode actually useful, `consul-dataplane` vendors the [`hashicorp/go-discover` binary](https://github.com/hashicorp/consul-dataplane/blob/23748fbd2bb740b1a2fecaf58bc5b5a38d67d1d0/Dockerfile#L82). This does the same to make sure we actually have useful "discovery" binaries on disk for any `exec=...` host strings passed to `consul-server-connection-manager`.
Additionally, since we execute in the context of the envoy container rather than our own envoy vendored container (a deliberate decision early on to avoid having to rev our own containers if envoy CVEs dropped), I added a `PATH` environment variable that I believe should be sufficient for executing both `discover` and …
=> Add go-discover binary for exec-based discovery

Dockerfile
https://github.com/hashicorp/consul-api-gateway/pull/446 Added `go-discover` to our containers and slightly changed our init container process. I forgot to add the `COPY` command to 1 of the 3 docker targets in our Dockerfile. This fixes that.
=> Add forgotten COPY command in default release docker target

dev/config/helm/consul.yaml, dev/config/k8s/service-account-secret.yaml, dev/config/k8s/service-account.yaml, dev/run
With Kubernetes 1.24, Service Accounts no longer get a secret with an access token by default.
- Added a step in the `./dev/run` demo that creates the secret. 
- Changed how the secret is accessed in accordance with 1.24's changes. 
- Removed the pinned Consul version from the Helm chart, now we can use what the Consul-k8s Helm chart uses by default.
- Set versions for K8s and Consul-k8s as constants at the top of the file so we can more easily update them in the future.
I chose 1.24 as the K8s version instead of 1.25 because I think Consul-k8s still has some gaps in supporting 1.25.
- Ran through [this onboarding doc](https://github.com/hashicorp/consul-api-gateway/blob/main/dev/docs/getting-started.md)
You may also run through the onboarding if you so desire.
> Run `make …
=> Update `./dev/run` for Kubernetes 1.24

.changelog/450.txt, config/crd/bases/api-gateway.consul.hashicorp.com_gatewayclassconfigs.yaml, internal/k8s/builder/builder.go, internal/k8s/builder/gateway.go, internal/k8s/builder/testdata/clusterip.deployment.golden.yaml, internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml, internal/k8s/builder/testdata/max-instances.deployment.golden.yaml, internal/k8s/builder/testdata/min-instances.deployment.golden.yaml, internal/k8s/builder/testdata/multiple-instances.deployment.golden.yaml, internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml, internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml, pkg/apis/v1alpha1/types.go
This adds support for setting the `CONSUL_PARTITION` and `CONSUL_TLS_SERVER_NAME` environment variables to support some of our changes for agentless.
Installed via helm and saw the values being set and the container starting up even when the values are empty.
=> Add TLS server name and partition CRD extensions

.github/workflows/conformance_with_build.yml, internal/commands/exec/command.go, internal/commands/exec/command_test.go, internal/commands/exec/exec_test.go, internal/commands/server/command.go, internal/commands/server/server.go, internal/consul/connection.go, internal/k8s/builder/gateway.go, internal/k8s/builder/testdata/clusterip.deployment.golden.yaml, internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml, internal/k8s/builder/testdata/max-instances.deployment.golden.yaml, internal/k8s/builder/testdata/min-instances.deployment.golden.yaml, internal/k8s/builder/testdata/multiple-instances.deployment.golden.yaml, internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml, internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
Add an opt-in value for trying to use the new dynamic server discovery components. This is needed because agent (non-server) nodes don't have the requisite gRPC endpoints to actually use the connection manager library. When the `CONSUL_DYNAMIC_SERVER_DISCOVERY` is not set, then we do things in the "old way" without gRPC, otherwise if it's set we know we're talking to a server and can use gRPC.
Manually w/ Consul 1.12 + 1.13 and consul-k8s 0.49.1 and consul-k8s main branch in both agent and agentless mode pending my PR that I'll link here.
=> Add fallback to no gRPC

CHANGELOG.md, README.md, config/deployment/deployment.yaml, dev/docs/example-setup.md, dev/docs/supported-features.md
Consul API Gateway version being released: `0.5.0`
Now requires:
- consul: `1.12`
- consul-k8s: `0.49.1`
=> Prepare for release of v0.5.0

.changelog/459.txt, internal/commands/exec/command.go, internal/commands/exec/exec.go, internal/envoy/manager.go
This adds the simplest path for supporting the helm option `externalServer.useSystemRoots`. Since the controller always passes in a value to the deployment via `CONSUL_CACERT` when the controller knows that the Consul connections are served over TLS, we leverage the fact that it's going to write an empty file to disk that the deployment will then try and use as a file.
Rather than doing a larger re-write of the deployment code to handle cases in which TLS is configured but no certs are passed in (when you want to validate with system-wide certs), I added some code that handles the invalid certificates being passed in, in which case we just fallback to using the system-wide certs. What this entails is:
1. Ensuring that the file passed in `CONSUL_CACERT` is valid.
2. If it isn't, unsetting …
=> Add fix for when we need to use the system-wide trusted CAs

CHANGELOG.md, README.md, internal/k8s/builder/testdata/clusterip.deployment.golden.yaml, internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml, internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml, internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml, internal/version/version.go
Consul API Gateway version being released: `0.5.1`
Now requires:
- consul: `1.12.0`
- consul-k8s: `0.49.1`
=> Prepare for release of v0.5.1

.copywrite.hcl
During work on #470, I mistakenly gave a `copyright_year` date of 2022 instead of 2021, when this project was originally created. This has the potential to cause license audits to fail, as `copywrite` will expect the attribution header on the `LICENSE` file to match whatever is in this `.copywrite.hcl` config.
=> Fix copyright year attribute

.changelog/483.txt, internal/commands/server/k8s_e2e_test.go, internal/k8s/controller.go, internal/testing/e2e/consul.go, internal/testing/e2e/environment.go, internal/testing/e2e/gateway.go, internal/testing/e2e/stack.go
Always map the `"default"` Consul namespace to the empty string in the memory backend store, for compatibility with Consul OSS and the logic to [parse the namespace of a Gateway from the SPIFFE URI](https://github.com/hashicorp/consul-api-gateway/blob/v0.5.1/internal/envoy/middleware.go#L112-L114), used when [reading a Gateway from a store backend](https://github.com/hashicorp/consul-api-gateway/blob/v0.5.1/internal/envoy/middleware.go#L79-L85).
This Consul namespace mapper function is already called when [reconciling a Gateway to a backend store](https://github.com/hashicorp/consul-api-gateway/blob/v0.5.1/internal/k8s/reconciler/manager.go#L180-L192), but the corresponding lookup fails with Consul Enterprise when `--consul-destination-namespace` is set to `"default"` because of the …
=> k8s/controller: always map "default" Consul namespace to empty string

internal/commands/server/k8s_e2e_test.go, internal/testing/e2e/service.go
This change is needed when running our e2e tests against Consul v1.15-dev, to accommodate the additional XForwardedClientCert (XFCC) logic added in https://github.com/hashicorp/consul/pull/15906
Thanks to @hashi-derek and @erichaberkorn for helping track this down and find the necessary fix!
CI e2e tests with Consul v1.15-dev should be passing once again with this change applied.
The consul-server-connection-manager bump should be removed before merging and handled separately in #484, I just wanted to minimize flakiness for initial review.
Confirm Consul v1.15-dev e2e tests are passing.
> Entries should use imperative present tense …
=> e2e: increase RegEx max program size in Envoy mesh service bootstrap template

go.mod, go.sum, internal/consul/connection.go
This resolves test flakiness issues caused by the un-threadsafety of registering a gRPC balancer in `NewWatcher` rather than an `init()` function. This didn't cause problems in actual deployments, but could happen when in our test suite when multiple calls to `NewWatcher` happened concurrently.
- Updates to a new version of consul-server-connection-manager which removes the gRPC custom balancer implementation and switches to the default [`pick_first`](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md#pick_first) balancer.
- Removes the now-unnecessary `globalWatcherMutex` (added in https://github.com/hashicorp/consul-api-gateway/pull/449)
- Removes an unneeded context cancellation call from the `client.WatchServers` method which was responsible for a race condition occurring …
=> deps: update consul-server-connection-manager

.changelog/505.txt, CHANGELOG.md, internal/commands/server/command.go, internal/commands/server/k8s_e2e_test.go, internal/consul/connection.go, internal/consul/namespaces.go, internal/k8s/config.go, internal/k8s/controller.go, internal/k8s/reconciler/deployer.go, internal/k8s/reconciler/statuses.go
When new namespace is created we should automatically apply the `cross-namespace-policy` policy to the newly created namespace to ensure cross namespace communication is allowed. 
Fixes #510 
* Clone the files from the following gist: https://gist.github.com/jm96441n/7e005c82fa918b7b73c11abb617b4998
* Replace the `<YOUR ENTERPRISE KEY>` with a key for enterprise consul in the `deploy.sh` file
* From the api-gw repo run `make docker/dev` on the main branch (without these changes)
* Run the `deploy.sh` script
* After that finishes from the terminal run `curl 0:30602 -vv --header 'Host: nginx.green.daskt.nsbug.it'` and you should see a `503` error along with `no healthy upstream`
* In the consul UI if you select `Manage Namespaces` from the `Namespaces` drop down you will see the `green` …
=> Fix bug with cross namespace policy

.changelog/521.txt, internal/k8s/builder/builder.go, internal/k8s/builder/testdata/clusterip.deployment.golden.yaml, internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml, internal/k8s/builder/testdata/max-instances.deployment.golden.yaml, internal/k8s/builder/testdata/min-instances.deployment.golden.yaml, internal/k8s/builder/testdata/multiple-instances.deployment.golden.yaml, internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml, internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
The default envoy image (v1.21) is no longer compatible with consul 1.15, this PR bumps that to `1.24` to maintain compatability.
Ran the tests.
Code review, run the tests
=> Bump default envoy image

.github/workflows/prepare_release.yml
The `ELEVATED_GITHUB_TOKEN` that we were previously using no longer works for branch + PR creation due to new enforcement of SSO requirement.
This change enables the specific permissions required on the default token handed to the workflow job and uses that default token instead of the elevated token. This mimics what we do over in [terraform-cdk](https://github.com/hashicorp/terraform-cdk/blob/57b1d12fe5fb3fcc3b89de8449c20ee13c62f9ac/.github/workflows/update-snapshots.yml#L148-L150).
=> Designate required permissions for release prep workflow

CHANGELOG.md, config/deployment/deployment.yaml, dev/docs/example-setup.md, dev/docs/supported-features.md
> **Note**: Had to do this manually since our Actions workflow is hitting issues with new SSO enforcement for tokens ([logs](https://github.com/hashicorp/consul-api-gateway/actions/runs/4324872794/jobs/7550276588)). Compare to #457 
Consul API Gateway version being released: `0.5.2` Now requires:
- consul: `1.12.0`
- consul-k8s: `0.49.1`
=> Prepare for release of v0.5.2

.github/workflows/ci.yml, internal/testing/e2e/consul.go
* Update CI matrix to use official 1.15 images
* Add 1.16-dev images to CI matrix
* Update e2e tests to use the 1.16-dev images by default 
Ran e2e tests locally
Code Review
=> Update testing matrix for 1.15 release

.changelog/537.txt, internal/commands/exec/command.go, internal/commands/exec/exec.go, internal/consul/registration.go, internal/consul/registration_test.go, internal/envoy/manager.go, internal/envoy/testdata/basic.golden.json, internal/envoy/testdata/empty.golden.json, internal/envoy/testdata/sds.golden.json, internal/envoy/testdata/tls.golden.json
Gateways deployed in non-default partitions weren't properly identifying themselves to xDS servers. This adds the required metadata into the envoy bootstrapping file to make sure that the envoy instance identifies itself properly.
Unit tests + verified manually.
=> Add partition identity to envoy deployment

CHANGELOG.md, config/deployment/deployment.yaml, dev/docs/example-setup.md, dev/docs/supported-features.md
> **Note**: Had to do this manually since our Actions workflow is hitting issues with new SSO enforcement for tokens. Compare to #527 
Consul API Gateway version being released: `0.5.3` Now requires:
- consul: `1.12.0`
- consul-k8s: `0.49.1`
=> Prepare for release of v0.5.3

.changelog/547.txt, internal/envoy/middleware.go
Adds SPIFFE parsing logic to handle paths for non-default partitions in Consul Enterprise.
- Configuring a Kubernetes cluster in a non-default partition requires external Consul servers, which our existing e2e framework does not support. Followup work will be adding a test deploying Consul API Gateway in a non-default partition to the github.com/hashicorp/consul-k8s/ repo, similar to the basic [`TestPartitions_Connect`](https://github.com/hashicorp/consul-k8s/blob/main/acceptance/tests/partitions/partitions_connect_test.go#L30) example.
- Confirm that deploying a Consul API Gateway in a Kubernetes cluster mapped to a non-default partition in Consul Enterprise succeeds with this patch applied.
- Check whether existing tweaked logic is reasonable, or whether we may want to switch to RegEx …
=> envoy: fix parse SPIFFE path parsing for non-default partitions

.changelog/595.txt, internal/k8s/service/resolver.go
Adds a nil check for the call back from Consul.
=> Fixes panic when nonexistent node is queried
