.github/workflows/ci.yml
dev/docs/example-setup.md
internal/testing/e2e/consul.go

- Consume Consul 1.11.3 for tests and examples
- CI passing
Checklist:

Consume Consul 1.11.3 in tests and examples

---

dev/docs/supported-features.md

- Update our feature list to show we support `TCPRoute`s, but with an explanation of some of our implementation limitations.

Add checked off box for TCPRoute feature

---

CHANGELOG.md
README.md
config/deployment/deployment.yaml
dev/docs/example-setup.md
dev/docs/supported-features.md
internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/version/version.go

- Updates for release
Checklist:

Update for release of v0.1.0

---

.github/workflows/build.yml

- Added LDFLAGS for setting proper revisions in release builds.

Add LDFLAGS to build command

---

.github/workflows/build.yml

* Add LDFLAGS to build command

Main merge to release/0.1.x

---

.release/ci.hcl

- add post-publish events to ci.hcl (CRT)
https://docs.google.com/document/d/1dUjhfqccvDnfnKkSPxjTu19zn9v4jSMT4_Lfh0mQ1yQ/edit?usp=sharing

Do not merge - add post publish events to ci.hcl

---

.release/ci.hcl

- add post-publish events to ci.hcl (CRT)
https://docs.google.com/document/d/1dUjhfqccvDnfnKkSPxjTu19zn9v4jSMT4_Lfh0mQ1yQ/edit?usp=sharing

Do not merge - Add post publish events release branch

---

internal/testing/e2e/consul.go

Added support for CONSUL_LICENSE_PATH
-running go test ./...
-ci/cd testing suite
- running go test ./..., ideally with CONSUL_LICENSE_PATH and CONSUL_LICENSE set
- testing suite 

Add support for CONSUL_LICENSE_PATH env variable

---

internal/adapters/consul/http.go
internal/adapters/consul/http_test.go
internal/adapters/consul/sync.go

As I'm working on better understanding how our controller interacts w/ Consul, I thought I'd add some docstrings and naming changes that helped me understand the code
I'd like for others to read through the docstrings and make sure that my understanding was correct as well as confirming whether the added docstrings are helpful.

Add docstrings + test coverage for route merging

---

.github/workflows/ci.yml
internal/commands/exec/exec_test.go
internal/consul/certmanager_test.go
internal/consul/intentions_test.go
internal/envoy/secrets.go
internal/store/memory/listener.go
internal/testing/e2e/consul.go
internal/testing/e2e/service.go
internal/testing/e2e/stack.go

- Changes to please the linter, no functional impact
- Show all linting failures on pull requests
🤖 tests pass

Address linting failures

---

.github/workflows/conformance.yml

Enable slack webhook
By opening this PR with the conformance test label

Enable slack webhook

---

dev/docs/supported-features.md

Updates the Supported Features doc for v0.2.0

supported-features: update for v0.2.0

---

.release/ci.hcl
CHANGELOG.md
README.md
config/deployment/deployment.yaml
dev/docs/example-setup.md
dev/docs/supported-features.md
internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/version/version.go

-Cut release 
-Followed the guide https://github.com/hashicorp/engineering-docs/blob/main/consul/consul-api-gateway/release-process.md
- Tests pass
- [X ] CHANGELOG entry added 

0.2.0 Release

---

.release/ci.hcl

Add promote-dev-docker step to ci.hcl

---

.release/ci.hcl

Add promote-dev-docker step to ci.hcl (#169)

---

CHANGELOG.md

Add missing heading for 0.2.1 to CHANGELOG
Read it

Add heading to CHANGELOG for 0.2.1

---

CHANGELOG.md

Add missing changelog heading for `0.2.1`

Add heading to CHANGELOG for 0.2.1 (#191)

---

.github/workflows/ci.yml

Update CI to use Consul 1.12.2
- Manual code inspection
- 🤖 tests pass
- Manual code inspection
- 🤖 tests pass

Update CI to use Consul 1.12.2

---

internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/version/version.go

Update version.go to reflect the next patch release in accordance with RelEng's new standard ([doc](https://docs.google.com/document/d/1ovhf8DmlXbsuc45HkN7LdsrS2J3evfSvcy2LPiyUgZ8/edit#heading=h.adgrzghnr96d))

Update version.go to reflect next patch release

---

.release/security-scan.hcl

Backporting #213 to our release branch so that CRT processes can succeed
#213 has already fixed this issue in `main`

Disable NVD scanning of binary on releases

---

.github/workflows/conformance.yml
internal/testing/conformance/consul-config.yaml

Add a test matrix for conformance tests verifying that API Gateway works w/ consul 1.11.x in addition to consul 1.12.x
🤖 tests pass
🤖 tests pass

Run conformance test for combinations of consul + consul-k8s

---

.github/workflows/conformance.yml

Update Slack message format to include job name for conformance runs
Manual inspection (string vars for formatting can be found [here](https://github.com/ravsamhq/notify-slack-action#extended-example-with-users-groups-mentions))

Update Slack message format to include job name for conformance runs

---

.github/workflows/conformance.yml

Update Helm Chart 0.45.0

---

internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/version/version.go

Update version on our release branch so that any developer builds reflect the next version to be released
🤖 tests pass

Update versions to target next patch release

---

internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/testing/conformance/consul-config.yaml
internal/version/version.go

Update version on our main branch so that any developer builds reflect the next version to be released
🤖 tests pass

Update versions to target next minor release

---

.github/actions/setup-eks/action.yml
.github/actions/teardown-eks/action.yml
.github/workflows/conformance.yml
.github/workflows/conformance_with_build.yml

Simplify the main conformance workflow by encapsulating AWS auth setup into the setup-eks action
See working conformance run on EKS for commit 89cd3763ec7dd6420a67a7a0705de65b89aee5db
See above

Integrate AWS auth into setup-eks action

---

.github/actions/teardown-eks/action.yml

--wait flag missing

---

.github/workflows/conformance.yml

**Note** Followup for https://github.com/hashicorp/consul-api-gateway/pull/250
A branch trigger for testing was unintentionally merged in, just removing it

Remove branch trigger for full conformance run leftover from testing

---

.github/workflows/backport.yml

Backport assistant workflow
Labels on this PR

Backport assistant config

---

internal/testing/conformance/kustomization.yaml

Remove now-unnecessary patch for upstream conformance resources

---

internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/version/version.go

Bump version to next patch release for the `release/0.4.x` branch. This will allow future work-in-progress to be tagged correctly.

Bump version to next patch release

---

.github/actions/setup-kind/action.yml

Update conformance tests to run on k8s 1.24
:robot: tests pass

Run conformance tests on k8s 1.24

---

Makefile
scripts/e2e_local.sh

Add a make target to run e2e tests
Ran locally
Code review, can run locally to test out as well

QoL add e2e make target

---

internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/version/version.go

One last change I missed, actually revving the binary's version in code.

Rev version for 0.5.3 release

---

CHANGELOG.md
config/deployment/deployment.yaml
dev/docs/example-setup.md
dev/docs/supported-features.md

Manual changes for Releasing v0.5.5

Prepare for release of v0.5.5

---

internal/k8s/builder/testdata/clusterip.deployment.golden.yaml
internal/k8s/builder/testdata/loadbalancer.deployment.golden.yaml
internal/k8s/builder/testdata/static-mapping.deployment.golden.yaml
internal/k8s/builder/testdata/tls-cert.deployment.golden.yaml
internal/version/version.go

Updates missed version updates for release of 0.5.5

Updates missed versions for release of 0.5.5

---

README.md

Update README.md - Add note about where to file issues for consul-k8s and consul
